### PR TITLE
Resolved #324

### LINKED ISSUE #324: AutoBuild fails at FastJuetFilter
After the merge of PR #315 , the nightly build failed with this error:
```
In file included from .sl73_gcc485/obj/StRoot/StarGenerator/FILT/FastJetFilter.cxx:1:0:
.sl73_gcc485/obj/StRoot/StarGenerator/FILT/FastJetFilter.h:14:32: fatal error: fastjet/PseudoJet.hh: No such file or directory
 #include <fastjet/PseudoJet.hh>
                                ^
compilation terminated.
 cons: *** [.sl73_gcc485/obj/StRoot/StarGenerator/FILT/FastJetFilter.o] Error 1 
cons: errors constructing .sl73_gcc485/obj/StRoot/StarGenerator/FILT/FastJetFilter.o
```

### PR DESCRIPTION
**Pull request by klendathu2k**

### CODE REVIEW

**Review by genevb — APPROVED** [review]
I don't see a way to do it more granularly with the current file placement. I guess the alternative is to move different filters into different subdirectories?

**Comment by genevb** [comment]
An open question: why did the [compilation succeed](https://github.com/star-bnl/star-sw/runs/5450790562?check_suite_focus=true#step:3:24883) on github for #315 ?

-Gene

**Comment by plexoos** [comment]
> An open question: why did the [compilation succeed](https://github.com/star-bnl/star-sw/runs/5450790562?check_suite_focus=true#step:3:24883) on github for #315 ?

Because `FASTJET_DIR` is explicitly defined in the environment:

https://github.com/star-bnl/star-sw/blob/43448bc3aaeb2fc8c7ff05376dc73d07f1630080/docker/Dockerfile.root5#L93

**Review by plexoos — APPROVED** [review]
