### ISSUE TITLE
AutoBuild fails after merging #48

### ISSUE THREAD

**Issue by plexoos** [star-bnl/star-sw#73]
Gene reported:

Looks like this change (https://github.com/star-bnl/star-sw/commit/816f58981e2e75332508af1862f0ca5ca687aa55) broke the nightly build:
https://www.star.bnl.gov/public/comp/prod/Sanity/AutoBuild.html

.sl73_gcc485/OBJ/StRoot/StarGenerator/StarLight/StarLightGen.o: In functionStarGenerator::FillUser(StarGenEvent*)':
/afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_gcc485/OBJ/StRoot/StarGenerator/StarLight/StarLightGen.cxx:19: multiple definition of rndm_' .sl73_gcc485/OBJ/StRoot/StarGenerator/StarLight/StarLight.o:/afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_gcc485/OBJ/StRoot/StarGenerator/StarLight/StarLight.cxx:19: first defined here collect2: error: ld returned 1 exit status

**Comment by plexoos** [comment]
AutoBuild should remove the old object file `/afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_gcc485/obj/StRoot/StarGenerator/StarLight/StarLight.o` along with the links to the removed source files, otherwise both the old and new files are being linked into the library. Here is what causes the conflict:

```
$ ls -l /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_gcc485/obj/StRoot/StarGenerator/StarLight/StarLight.*
lrwxr-xr-x 1 starlib rhstar     59 May 17 20:22 /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_gcc485/obj/StRoot/StarGenerator/StarLight/StarLight.cxx -> ../../../../../StRoot/StarGenerator/StarLight/StarLight.cxx
lrwxr-xr-x 1 starlib rhstar     57 May 17 20:22 /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_gcc485/obj/StRoot/StarGenerator/StarLight/StarLight.h -> ../../../../../StRoot/StarGenerator/StarLight/StarLight.h
-rw-r--r-- 1 starlib rhstar 429200 May 17 22:16 /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_gcc485/obj/StRoot/StarGenerator/StarLight/StarLight.o

$ ls -l /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_gcc485/obj/StRoot/StarGenerator/StarLight/StarLightGen.*
lrwxr-xr-x 1 starlib rhstar     62 Jul 26 23:09 /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_gcc485/obj/StRoot/StarGenerator/StarLight/StarLightGen.cxx -> ../../../../../StRoot/StarGenerator/StarLight/StarLightGen.cxx
lrwxr-xr-x 1 starlib rhstar     60 Jul 26 23:09 /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_gcc485/obj/StRoot/StarGenerator/StarLight/StarLightGen.h -> ../../../../../StRoot/StarGenerator/StarLight/StarLightGen.h
-rw-r--r-- 1 starlib rhstar 429540 Jul 26 23:09 /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_gcc485/obj/StRoot/StarGenerator/StarLight/StarLightGen.o
```

**Comment by plexoos** [comment]
https://www.star.bnl.gov/public/comp/prod/Sanity/AutoBuild-64bits.html

The 64-bit build does not show the same error because it has not picked up the new change for some reason:

```
$ ls -l /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_x8664_gcc485/obj/StRoot/StarGenerator/StarLight/StarLight.*
lrwxr-xr-x 1 starlib rhstar      59 May 18 07:29 /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_x8664_gcc485/obj/StRoot/StarGenerator/StarLight/StarLight.cxx -> ../../../../../StRoot/StarGenerator/StarLight/StarLight.cxx
lrwxr-xr-x 1 starlib rhstar      57 May 18 07:29 /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_x8664_gcc485/obj/StRoot/StarGenerator/StarLight/StarLight.h -> ../../../../../StRoot/StarGenerator/StarLight/StarLight.h
-rw-r--r-- 1 starlib rhstar  591904 May 18 08:28 /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_x8664_gcc485/obj/StRoot/StarGenerator/StarLight/StarLight.o
-rwxr-xr-x 1 starlib rhstar 2365560 May 18 08:28 /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_x8664_gcc485/obj/StRoot/StarGenerator/StarLight/StarLight.so

$ ls -l /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_x8664_gcc485/obj/StRoot/StarGenerator/StarLight/StarLightGen.*
ls: cannot access /afs/.rhic.bnl.gov/star/packages/release32/gitdev/.sl73_x8664_gcc485/obj/StRoot/StarGenerator/StarLight/StarLightGen.*: No such file or directory
```

**Comment by genevb** [comment]
On Jul 27, 2021, at 1:13 AM, Dmitri Smirnov ***@***.******@***.***>> wrote:



https://www.star.bnl.gov/public/comp/prod/Sanity/AutoBuild-64bits.html

The 64-bit build does not show the same error because it has not picked up the new change for some reason.

The 64-bit AutoBuild finished just a minute after you noted this, and it did see the same error as the 32-bit.

So I deleted the old StarGenerator/StarLight/StarLight.* object and source code files and re-ran AutoBuild. I found it failed again as I had only deleted the soft links to the source code, but the source code files also needed to be deleted. Now it succeeds.

-Gene
