### ISSUE TITLE
AutoBuild fails at FastJuetFilter

### ISSUE THREAD

**Issue by genevb** [star-bnl/star-sw#324]
After the merge of PR #315 , the nightly build failed with this error:
```
In file included from .sl73_gcc485/obj/StRoot/StarGenerator/FILT/FastJetFilter.cxx:1:0:
.sl73_gcc485/obj/StRoot/StarGenerator/FILT/FastJetFilter.h:14:32: fatal error: fastjet/PseudoJet.hh: No such file or directory
 #include <fastjet/PseudoJet.hh>
                                ^
compilation terminated.
 cons: *** [.sl73_gcc485/obj/StRoot/StarGenerator/FILT/FastJetFilter.o] Error 1 
cons: errors constructing .sl73_gcc485/obj/StRoot/StarGenerator/FILT/FastJetFilter.o
```

**Comment by genevb** [comment]
I'm not sure the problem was with PR #315 ; AutoBuild doesn't seem to be getting the right files into the appropriate directories. I'm Investigating.

**Comment by genevb** [comment]
Scratch that....AutoBuild appears to have worked fine (I let myself get confused about something that was trivial), and the issue is in fact with the PR. I backstepped DEV to use the SHA from the commit prior to the merger of PR #315 and that allowed DEV to compile, which is good because that's probably what we can use for SL22a and it allows us to run the nightly tests with that state of code. So as of now, DEV is one step back from `main` and is using `9978fad2aa62f6d8e53918af9bf84bb766d0e7c9`.

**Comment by klendathu2k** [comment]
I'll take a look at this shortly.   cons should have been modified to set the include path for the fastjet package, and the CI build succeeded / allowed the merge... so there is something odd here.

**Comment by genevb** [comment]
Confirmed: AutoBuild succeeded after merging #325 .
